# Change these first
owner: attentiontech # Your GitHub organization or username, where this repository lives
repo: status-page # The name of this repository

sites:
  - name: Attention
    url: https://www.attention.tech/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.attention.tech
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Attention Status
  introTitle: "Status Page"
  introMessage: ""
  navbar:
    - title: Status
      href: https://www.attention.tech/
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
